### ISSUE TITLE
Fine-grained speed setting

### ISSUE THREAD

**Issue by eliezedeck** [spance/suft#7]
The `Params.Bandwidth` is set as int64, which means I cannot set a speed lower than 1 because it will naturally be rounded. This means, that the minimum speed will be 1024 KB/s; this is too fast for many use cases.

For example, my case requires 256 kbps, which is just about 32 KB/s.

I propose to add a `Endpoint.SetBPSBandwidth(bytespersecond int64)`. After all, the library itself sets the internal speed to **bytes per second** already.

**Comment by spance** [comment]
the unit of `Params.Bandwidth` is `mbps`( 1mbps=128KB/s), and the suft is designed to improve transmitting experience over long distances middle or high speed network(such as 10mbps/100mbps).

Like you in the low-speed network, you can directly use tcp transmission. And there is no need to use the enhanced transmission method, because your access network is only so little.

**Comment by eliezedeck** [comment]
Well, I disagree. But anyway, I have used something else, as MTU is no working as expected too. So, I don't think it's not for my project, and the license is not fitting as well, GPL ain't cool.

Thanks anyway.
